### ISSUE TITLE
Support Task install scripts

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/hub#127]
### Feature request

When installing a Task or Pipeline, allow an installation script to be run so that dependent resources can be created alongside the Tekton resources.

### Use case

In https://github.com/tektoncd/catalog/pull/556 a Task author has provided a number of helpful installation scripts that can be used to setup a ConfigMap & credential Secrets that are needed for their Task to operate. The ConfigMap in particular is a long-lived piece of configuration that makes sense to include alongside the main installation of the Task.  However, at the moment, I'm not sure there's a good way to get from browsing the Hub to this installation script to set up the ConfigMap.

So the idea would be to run an installation script as part of installing Tasks from the Hub interface. Maybe the installation script could itself be a Task for the Hub to run?

```yaml
# hypothetical task/orka-full/0.1/hub-install.yaml
kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: install-orka-full-catalog-task
spec:
  params:
  - name: namespace
    default: "default"
  - name: api-endpoint
    default: "http://10.221.188.100"
  image: bitnami/kubectl
  script: |
    cat > configmap.yaml << 'EOF'
    kind: ConfigMap
    apiVersion: v1
    metadata:
      name: orka-tekton-config
    stringData:
      ORKA_API: $(params.api-endpoint)
    EOF
    kubectl apply -n $(params.namespace) -f ./configmap.yaml
```

From this the Hub could generate a UI for the params, asking the user to enter the required information or accept the defaults.  Then Hub could run the Task in the cluster, installing the dependent resources.

Edit to add: Maybe the Task's catalog directory could be mounted into its `hub-install` Task as a Workspace so that the scripts are accessible?
