### ISSUE TITLE
Catalog is not rendered while using Github Enterprise

### ISSUE THREAD

**Issue by spuranam** [tektoncd/hub#314]
I have pretty run of the mill deployment of Tekton-Hub, i was able to get all components of the stack stood up using these [deployment instructions](https://github.com/tektoncd/hub/blob/main/docs/DEPLOYMENT.md)

# Expected Behavior
See the tekton catalog hosted in GitHub Enterprise is rendered 

# Actual Behavior
After completing this [Add resources in DB](https://github.com/tektoncd/hub/blob/main/docs/DEPLOYMENT.md#add-resources-in-db), i do not see the catalog being rendered. What i do see is a error message in browsers "developer console" that endpoint "https://hub-api.foo.com/resources" is returns a "404", inspecting this endpoint returns this error:

```
{"name":"not-found","id":"nV1CgZbQ","message":"resource not found","temporary":false,"timeout":false,"fault":false}
``` 

Not really sure what i should i be looking for to further diagnose the problem?

# Additional Info

- UI Screenshots(if applicable)

<img width="1465" alt="ui-1" src="https://user-images.githubusercontent.com/1459929/131260293-354bccbd-b9d5-4b1a-998c-909386d64af1.png">

<img width="1460" alt="ui-2" src="https://user-images.githubusercontent.com/1459929/131260303-70fd874b-7ab3-47c8-bd53-d81e8485dda0.png">

**Comment by PuneetPunamiya** [comment]
@spuranam Thanks for opening up an issue with such a great shot

Could you please share the records in the resource table from db, because I think there are no resources present in the db and the catalog refresh is not done 

Db query to get the resources count from the table 

```
select count(*) from resources
```

Also could you please share the `config.yaml` file you have used ??

**Comment by spuranam** [comment]
@PuneetPunamiya 

Yes there are no resources present in the db, but i did run above command and it returned the expected output.

```bash
curl -X POST -H "Authorization: ${jwt_token}" https://hub-api.caasdev.foo.com/catalog/tekton/refresh

{"id":2,"catalogName":"tekton","status":"queued"}
```

```bash
POD=$(kubectl -n tekton-hub get pods -l app.kubernetes.io/name=postgres --no-headers=true -o=custom-columns=NAME:.metadata.name | head -n1)
kubectl -n tekton-hub exec ${POD} -- psql -d "tektonhub" -c "select count(*) from resources;"
 count
-------
     0
(1 row)
```

## Config.yaml
```yaml
categories:
  - name: Automation
    tags: [ansible, boskos, ci, jenkins, operator, release-automation, tekton]
  - name: Build Tools
    tags: [build-tool]
  - name: CLI
    tags: [cli, kubectl]
  - name: Cloud
    tags: [aws, azure, cloud, gcp, gke, openshift]
  - name: Deploy
    tags: [canary, deploy, deployment, helm, istio]
  - name: Editor
    tags: [editor, formatter, lint, linter, pylint]
  - name: Git
    tags: [git, github, gitlab, scm]
  - name: Image Build
    tags: [docker, image-build, build, build-image]
  - name: Language
    tags: [golang, python]
  - name: Messaging
    tags: [mail, messaging]
  - name: Monitoring
    tags: [prometheus]
  - name: Notification
    tags: [notification]
  - name: Others
    tags:
      [
        annotations,
        delete,
        dind,
        download,
        gate,
        generic,
        package,
        powershell,
        pwsh,
        remote,
        search,
        scorecard,
      ]
  - name: Security
    Tags: [security, ssh, tokens]
  - name: Storage
    Tags: [gcs]
  - name: Test Framework
    tags: [coverage, test, pytest]

catalogs:
  #- name: tekton
  #  org: tektoncd
  #  type: community
  #  url: https://github.com/tektoncd/catalog
  #  revision: main
  - name: tekton
    org: fads
    type: official
    url: https://github.foo.com/tkn/tekton-catalog
    revision: master
    #contextDir(Optional): Path to resource dir

scopes:
  - name: agent:create
    users: [spuranam]
  - name: catalog:refresh
    users: [spuranam]
  - name: config:refresh
    users: [spuranam]

default:
  scopes:
    - rating:read
    - rating:write
# Template
# catalogs:
#   - name: Name of Catalog
#     org:  Organization of Catalog
#     type: Type of Catalog [official, verified, community]
#     url:  URL of repository
#     revision: Branch of repository
#     contextDir(Optional): Path to resource dir
```
